#ifndef IFB_ENGINE_INTERNAL_CONFIG_HPP
#define IFB_ENGINE_INTERNAL_CONFIG_HPP

#ifndef IFB_ENGINE_CONFIG_MEMORY_STACK_SIZE_KB
    #define IFB_ENGINE_CONFIG_MEMORY_STACK_SIZE_KB 64
#endif //IFB_ENGINE_CONFIG_MEMORY_STACK_SIZE_KB

#endif //IFB_ENGINE_INTERNAL_CONFIG_HPP