#include <ifb.hpp>

#include "ifb-engine-internal-context.hpp"

#ifndef IFB_ENGINE_INTERNAL_CONFIG_HPP
#define IFB_ENGINE_INTERNAL_CONFIG_HPP

#ifndef  IFB_ENGINE_CONFIG_MEMORY_STACK_SIZE_KB
#define  IFB_ENGINE_CONFIG_MEMORY_STACK_SIZE_KB 64
#endif //IFB_ENGINE_CONFIG_MEMORY_STACK_SIZE_KB

#ifndef  IFB_ENGINE_CONFIG_MEMORY_RESERVATION_SIZE_GB
#define  IFB_ENGINE_CONFIG_MEMORY_RESERVATION_SIZE_GB 4
#endif //IFB_ENGINE_CONFIG_MEMORY_RESERVATION_SIZE_GB

namespace ifb_engine {

    inline const IFBB8 config_load();
};

#endif //IFB_ENGINE_INTERNAL_CONFIG_HPP