#ifndef ITFLIESBY_MATH_HPP
#define ITFLIESBY_MATH_HPP

#define ITFLIESBY_MATH_KILOBYTES(value) (value * 1024)
#define ITFLIESBY_MATH_MEGABYTES(value) (ITFLIESBY_MATH_KILOBYTES(value) * 1024)
#define ITFLIESBY_MATH_GIGABYTES(value) (ITFLIESBY_MATH_MEGABYTES(value) * 1024)

#endif //ITFLIESBY_MATH_HPP